

-- ===== supabase-setup.sql =====
-- ============================================================
-- Dorado Artículos de Pesca - CONFIGURACIÓN SEGURA DE SUPABASE
-- Ejecutar UNA VEZ en Supabase > SQL Editor.
-- Antes: crear el usuario administrador en Authentication > Users.
-- Después: reemplazar ADMIN_EMAIL_AQUI por su email y ejecutar
-- solamente el bloque final de "DAR PERMISO DE ADMIN".
-- ============================================================

create extension if not exists pgcrypto;

-- 1) Tabla de administradores
create table if not exists public.admin_users (
    user_id uuid primary key references auth.users(id) on delete cascade,
    created_at timestamptz not null default now()
);

alter table public.admin_users enable row level security;

drop policy if exists "Admin can read own admin row" on public.admin_users;
create policy "Admin can read own admin row"
on public.admin_users
for select
to authenticated
using (user_id = (select auth.uid()));

-- Función segura reutilizable por las políticas
create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
    select exists(
        select 1
        from public.admin_users
        where user_id = auth.uid()
    );
$$;

revoke all on function public.is_admin() from public;
revoke execute on function public.is_admin() from public, anon;
grant execute on function public.is_admin() to authenticated;

-- 2) Productos: crear la tabla base si todavía no existe
create table if not exists public.productos (
    id bigint generated by default as identity primary key,
    nombre text not null,
    descripcion text,
    caracteristicas text,
    precio numeric(12,2) not null default 0,
    imagen text,
    imagenes text[] not null default '{}'::text[],
    categoria text,
    stock integer not null default 0,
    activo boolean not null default true,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

-- Completar columnas si la tabla ya existía de una versión anterior
alter table public.productos
    add column if not exists descripcion text,
    add column if not exists caracteristicas text,
    add column if not exists precio numeric(12,2) not null default 0,
    add column if not exists imagen text,
    add column if not exists categoria text,
    add column if not exists stock integer not null default 0,
    add column if not exists activo boolean not null default true,
    add column if not exists created_at timestamptz not null default now(),
    add column if not exists updated_at timestamptz not null default now();

do $$
begin
    if not exists (
        select 1 from pg_constraint
        where conname = 'productos_precio_no_negativo'
          and conrelid = 'public.productos'::regclass
    ) then
        alter table public.productos
            add constraint productos_precio_no_negativo check (precio >= 0) not valid;
        alter table public.productos validate constraint productos_precio_no_negativo;
    end if;

    if not exists (
        select 1 from pg_constraint
        where conname = 'productos_stock_no_negativo'
          and conrelid = 'public.productos'::regclass
    ) then
        alter table public.productos
            add constraint productos_stock_no_negativo check (stock >= 0) not valid;
        alter table public.productos validate constraint productos_stock_no_negativo;
    end if;
end $$;

alter table public.productos enable row level security;

drop policy if exists "Public can view active products" on public.productos;
create policy "Public can view active products"
on public.productos
for select
to anon, authenticated
using (activo = true or public.is_admin());

drop policy if exists "Admins can insert products" on public.productos;
create policy "Admins can insert products"
on public.productos
for insert
to authenticated
with check (public.is_admin());

drop policy if exists "Admins can update products" on public.productos;
create policy "Admins can update products"
on public.productos
for update
to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "Admins can delete products" on public.productos;
create policy "Admins can delete products"
on public.productos
for delete
to authenticated
using (public.is_admin());

-- 3) Pedidos
create table if not exists public.pedidos (
    id uuid primary key default gen_random_uuid(),
    created_at timestamptz not null default now(),
    cliente_nombre text not null,
    cliente_email text not null,
    cliente_telefono text not null,
    domicilio text not null,
    ciudad text not null,
    provincia text not null,
    codigo_postal text not null,
    metodo_entrega text not null default 'retiro',
    notas text,
    total numeric(12,2) not null check (total >= 0),
    estado text not null default 'pendiente',
    preparacion_estado text not null default 'nuevo',
    tracking_token uuid not null default gen_random_uuid(),
    mp_preference_id text,
    mp_payment_id text
);

alter table public.pedidos
    add column if not exists preparacion_estado text not null default 'nuevo',
    add column if not exists tracking_token uuid default gen_random_uuid();

update public.pedidos
set tracking_token = gen_random_uuid()
where tracking_token is null;

alter table public.pedidos
    alter column tracking_token set default gen_random_uuid(),
    alter column tracking_token set not null;

create unique index if not exists pedidos_tracking_token_uidx
on public.pedidos(tracking_token);

create index if not exists pedidos_created_at_idx
on public.pedidos(created_at desc);

create index if not exists pedidos_estado_idx
on public.pedidos(estado);

alter table public.pedidos enable row level security;

drop policy if exists "Admins can view orders" on public.pedidos;
create policy "Admins can view orders"
on public.pedidos
for select
to authenticated
using (public.is_admin());

drop policy if exists "Admins can update orders" on public.pedidos;
create policy "Admins can update orders"
on public.pedidos
for update
to authenticated
using (public.is_admin())
with check (public.is_admin());

-- No se habilita INSERT/DELETE al navegador.
-- Los pedidos se crean y actualizan solo desde las funciones de Vercel
-- usando SUPABASE_SERVICE_ROLE_KEY.

-- 4) Ítems de pedido
create table if not exists public.pedido_items (
    id bigint generated by default as identity primary key,
    pedido_id uuid not null references public.pedidos(id) on delete cascade,
    producto_id bigint references public.productos(id) on delete set null,
    nombre text not null,
    cantidad integer not null check (cantidad > 0),
    precio_unitario numeric(12,2) not null check (precio_unitario >= 0)
);

create index if not exists pedido_items_pedido_id_idx
on public.pedido_items(pedido_id);

alter table public.pedido_items enable row level security;

drop policy if exists "Admins can view order items" on public.pedido_items;
create policy "Admins can view order items"
on public.pedido_items
for select
to authenticated
using (public.is_admin());

-- 5) Confirmación atómica del pago y descuento de stock.
-- El webhook llama esta función solamente después de verificar el pago
-- consultando directamente a Mercado Pago con el token privado.
create or replace function public.confirmar_pago_pedido(
    p_pedido_id uuid,
    p_payment_id text
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
    v_estado text;
    v_falta_stock boolean;
begin
    select estado
    into v_estado
    from public.pedidos
    where id = p_pedido_id
    for update;

    if not found then
        return jsonb_build_object('ok', false, 'reason', 'pedido_no_encontrado');
    end if;

    if v_estado = 'pagado' then
        return jsonb_build_object('ok', true, 'already_paid', true);
    end if;

    select exists(
        select 1
        from public.pedido_items i
        left join public.productos p on p.id = i.producto_id
        where i.pedido_id = p_pedido_id
          and (p.id is null or p.stock < i.cantidad)
    )
    into v_falta_stock;

    if v_falta_stock then
        update public.pedidos
        set estado = 'pagado_revisar_stock',
            mp_payment_id = p_payment_id
        where id = p_pedido_id;

        return jsonb_build_object('ok', false, 'reason', 'stock_insuficiente');
    end if;

    update public.productos p
    set stock = p.stock - i.cantidad,
        updated_at = now()
    from public.pedido_items i
    where i.pedido_id = p_pedido_id
      and i.producto_id = p.id;

    update public.pedidos
    set estado = 'pagado',
        mp_payment_id = p_payment_id
    where id = p_pedido_id;

    return jsonb_build_object('ok', true, 'paid', true);
end;
$$;

revoke all on function public.confirmar_pago_pedido(uuid,text) from public;
revoke all on function public.confirmar_pago_pedido(uuid,text) from anon;
revoke all on function public.confirmar_pago_pedido(uuid,text) from authenticated;
grant execute on function public.confirmar_pago_pedido(uuid,text) to service_role;

-- 6) Borrado seguro de pedidos desde el panel.
create or replace function public.admin_delete_orders(p_ids uuid[])
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
    v_deleted integer := 0;
begin
    if auth.uid() is null
       or not exists (
           select 1
           from public.admin_users
           where user_id = auth.uid()
       )
    then
        raise exception 'not_authorized' using errcode = '42501';
    end if;

    delete from public.pedidos
    where id = any(p_ids);

    get diagnostics v_deleted = row_count;
    return v_deleted;
end;
$$;

revoke all on function public.admin_delete_orders(uuid[]) from public;
revoke all on function public.admin_delete_orders(uuid[]) from anon;
grant execute on function public.admin_delete_orders(uuid[]) to authenticated;

-- 7) Límite anti-spam del checkout.
create table if not exists public.checkout_rate_limits (
    key_hash text primary key,
    window_started_at timestamptz not null default now(),
    request_count integer not null default 0 check (request_count >= 0),
    updated_at timestamptz not null default now()
);

alter table public.checkout_rate_limits enable row level security;

revoke all on table public.checkout_rate_limits from anon;
revoke all on table public.checkout_rate_limits from authenticated;

create or replace function public.consume_checkout_rate_limit(
    p_key_hash text,
    p_limit integer default 10,
    p_window_seconds integer default 600
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
    v_now timestamptz := now();
    v_started timestamptz;
    v_count integer;
    v_retry integer := 0;
begin
    if p_key_hash is null
       or length(p_key_hash) < 32
       or p_limit < 1
       or p_limit > 100
       or p_window_seconds < 60
       or p_window_seconds > 86400
    then
        raise exception 'invalid_rate_limit_input';
    end if;

    insert into public.checkout_rate_limits (
        key_hash, window_started_at, request_count, updated_at
    )
    values (p_key_hash, v_now, 1, v_now)
    on conflict (key_hash) do update
    set
        window_started_at = case
            when public.checkout_rate_limits.window_started_at
                 <= v_now - make_interval(secs => p_window_seconds)
            then v_now
            else public.checkout_rate_limits.window_started_at
        end,
        request_count = case
            when public.checkout_rate_limits.window_started_at
                 <= v_now - make_interval(secs => p_window_seconds)
            then 1
            else public.checkout_rate_limits.request_count + 1
        end,
        updated_at = v_now
    returning window_started_at, request_count
    into v_started, v_count;

    if v_count > p_limit then
        v_retry := greatest(
            1,
            ceil(
                extract(
                    epoch from (
                        v_started
                        + make_interval(secs => p_window_seconds)
                        - v_now
                    )
                )
            )::integer
        );

        return jsonb_build_object(
            'allowed', false,
            'retry_after', v_retry,
            'count', v_count
        );
    end if;

    delete from public.checkout_rate_limits
    where updated_at < v_now - interval '24 hours';

    return jsonb_build_object(
        'allowed', true,
        'retry_after', 0,
        'count', v_count
    );
end;
$$;

revoke all on function public.consume_checkout_rate_limit(text,integer,integer) from public;
revoke all on function public.consume_checkout_rate_limit(text,integer,integer) from anon;
revoke all on function public.consume_checkout_rate_limit(text,integer,integer) from authenticated;
grant execute on function public.consume_checkout_rate_limit(text,integer,integer) to service_role;

-- 8) Privilegios de tablas. RLS sigue siendo la barrera de autorización.
revoke all on table public.admin_users from anon;
revoke all on table public.pedidos from anon;
revoke all on table public.pedido_items from anon;
revoke all on table public.productos from anon;

grant select on table public.productos to anon;
grant select on table public.productos to authenticated;
grant insert, update, delete on table public.productos to authenticated;
grant select on table public.admin_users to authenticated;
grant select, update on table public.pedidos to authenticated;
grant select on table public.pedido_items to authenticated;

-- 9) Storage para imágenes de productos
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
    'productos',
    'productos',
    true,
    5242880,
    array['image/jpeg','image/png','image/webp']
)
on conflict (id) do update
set public = excluded.public,
    file_size_limit = excluded.file_size_limit,
    allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "Public can view product images" on storage.objects;
create policy "Public can view product images"
on storage.objects
for select
to public
using (bucket_id = 'productos');

drop policy if exists "Admins can upload product images" on storage.objects;
create policy "Admins can upload product images"
on storage.objects
for insert
to authenticated
with check (
    bucket_id = 'productos'
    and public.is_admin()
);

drop policy if exists "Admins can update product images" on storage.objects;
create policy "Admins can update product images"
on storage.objects
for update
to authenticated
using (
    bucket_id = 'productos'
    and public.is_admin()
)
with check (
    bucket_id = 'productos'
    and public.is_admin()
);

drop policy if exists "Admins can delete product images" on storage.objects;
create policy "Admins can delete product images"
on storage.objects
for delete
to authenticated
using (
    bucket_id = 'productos'
    and public.is_admin()
);

-- ============================================================
-- DAR PERMISO DE ADMIN
-- 1. Crear primero el usuario en Supabase > Authentication > Users.
-- 2. Cambiar el email de abajo.
-- 3. Ejecutar SOLO este bloque.
-- ============================================================

-- insert into public.admin_users (user_id)
-- select id
-- from auth.users
-- where lower(email) = lower('ADMIN_EMAIL_AQUI')
-- on conflict (user_id) do nothing;


-- ===== upgrade-final.sql =====
-- ============================================================
-- Dorado Artículos de Pesca - UPGRADE FINAL
-- Seguro para ejecutar sobre la base actual.
-- Incluye tracking, anti-spam, borrado admin y privilegios.
-- ============================================================

create extension if not exists pgcrypto;

alter table public.productos
    add column if not exists caracteristicas text;

alter table public.pedidos
    add column if not exists preparacion_estado text not null default 'nuevo',
    add column if not exists tracking_token uuid default gen_random_uuid();

update public.pedidos
set tracking_token = gen_random_uuid()
where tracking_token is null;

alter table public.pedidos
    alter column tracking_token set default gen_random_uuid(),
    alter column tracking_token set not null;

create unique index if not exists pedidos_tracking_token_uidx
on public.pedidos(tracking_token);

create or replace function public.admin_delete_orders(p_ids uuid[])
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
    v_deleted integer := 0;
begin
    if auth.uid() is null
       or not exists (
           select 1 from public.admin_users where user_id = auth.uid()
       )
    then
        raise exception 'not_authorized' using errcode = '42501';
    end if;

    delete from public.pedidos
    where id = any(p_ids);

    get diagnostics v_deleted = row_count;
    return v_deleted;
end;
$$;

revoke all on function public.admin_delete_orders(uuid[]) from public;
revoke all on function public.admin_delete_orders(uuid[]) from anon;
grant execute on function public.admin_delete_orders(uuid[]) to authenticated;

create table if not exists public.checkout_rate_limits (
    key_hash text primary key,
    window_started_at timestamptz not null default now(),
    request_count integer not null default 0 check (request_count >= 0),
    updated_at timestamptz not null default now()
);

alter table public.checkout_rate_limits enable row level security;
revoke all on table public.checkout_rate_limits from anon;
revoke all on table public.checkout_rate_limits from authenticated;

create or replace function public.consume_checkout_rate_limit(
    p_key_hash text,
    p_limit integer default 10,
    p_window_seconds integer default 600
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
    v_now timestamptz := now();
    v_started timestamptz;
    v_count integer;
    v_retry integer := 0;
begin
    if p_key_hash is null
       or length(p_key_hash) < 32
       or p_limit < 1
       or p_limit > 100
       or p_window_seconds < 60
       or p_window_seconds > 86400
    then
        raise exception 'invalid_rate_limit_input';
    end if;

    insert into public.checkout_rate_limits (
        key_hash, window_started_at, request_count, updated_at
    )
    values (p_key_hash, v_now, 1, v_now)
    on conflict (key_hash) do update
    set
        window_started_at = case
            when public.checkout_rate_limits.window_started_at
                 <= v_now - make_interval(secs => p_window_seconds)
            then v_now
            else public.checkout_rate_limits.window_started_at
        end,
        request_count = case
            when public.checkout_rate_limits.window_started_at
                 <= v_now - make_interval(secs => p_window_seconds)
            then 1
            else public.checkout_rate_limits.request_count + 1
        end,
        updated_at = v_now
    returning window_started_at, request_count
    into v_started, v_count;

    if v_count > p_limit then
        v_retry := greatest(
            1,
            ceil(extract(epoch from (
                v_started + make_interval(secs => p_window_seconds) - v_now
            )))::integer
        );

        return jsonb_build_object(
            'allowed', false,
            'retry_after', v_retry,
            'count', v_count
        );
    end if;

    delete from public.checkout_rate_limits
    where updated_at < v_now - interval '24 hours';

    return jsonb_build_object(
        'allowed', true,
        'retry_after', 0,
        'count', v_count
    );
end;
$$;

revoke all on function public.consume_checkout_rate_limit(text,integer,integer) from public;
revoke all on function public.consume_checkout_rate_limit(text,integer,integer) from anon;
revoke all on function public.consume_checkout_rate_limit(text,integer,integer) from authenticated;
grant execute on function public.consume_checkout_rate_limit(text,integer,integer) to service_role;

revoke all on table public.admin_users from anon;
revoke all on table public.pedidos from anon;
revoke all on table public.pedido_items from anon;
revoke all on table public.productos from anon;

grant select on table public.productos to anon;
grant select on table public.productos to authenticated;
grant insert, update, delete on table public.productos to authenticated;
grant select on table public.admin_users to authenticated;
grant select, update on table public.pedidos to authenticated;
grant select on table public.pedido_items to authenticated;


-- ===== product-gallery.sql =====
-- Dorado Artículos de Pesca — galería de imágenes por producto
-- Ejecutar una sola vez en Supabase SQL Editor.

alter table public.productos
add column if not exists imagenes text[] not null default '{}'::text[];

update public.productos
set imagenes = array[imagen]
where coalesce(array_length(imagenes, 1), 0) = 0
  and nullif(trim(imagen), '') is not null;

-- Mantiene imagen como principal por compatibilidad con carrito,
-- checkout y cualquier código anterior.
update public.productos
set imagen = imagenes[1]
where coalesce(array_length(imagenes, 1), 0) > 0
  and (
    nullif(trim(imagen), '') is null
    or imagen is distinct from imagenes[1]
  );


-- ===== security-hardening.sql =====
-- ============================================================
-- Dorado Artículos de Pesca — HARDENING DE SEGURIDAD
-- Ejecutar una sola vez en Supabase SQL Editor.
-- Compatible con la estructura actual.
-- ============================================================

-- 1) Rate limit genérico para APIs server-side.
create table if not exists public.api_rate_limits (
    key_hash text primary key,
    window_started_at timestamptz not null default now(),
    request_count integer not null default 0 check (request_count >= 0),
    updated_at timestamptz not null default now()
);

alter table public.api_rate_limits enable row level security;

revoke all on table public.api_rate_limits from anon;
revoke all on table public.api_rate_limits from authenticated;

create or replace function public.consume_api_rate_limit(
    p_key_hash text,
    p_limit integer default 30,
    p_window_seconds integer default 600
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
    v_now timestamptz := now();
    v_started timestamptz;
    v_count integer;
    v_retry integer := 0;
begin
    if p_key_hash is null
       or length(p_key_hash) < 32
       or p_limit < 1
       or p_limit > 500
       or p_window_seconds < 30
       or p_window_seconds > 86400
    then
        raise exception 'invalid_rate_limit_input';
    end if;

    insert into public.api_rate_limits (
        key_hash,
        window_started_at,
        request_count,
        updated_at
    )
    values (
        p_key_hash,
        v_now,
        1,
        v_now
    )
    on conflict (key_hash) do update
    set
        window_started_at = case
            when public.api_rate_limits.window_started_at
                 <= v_now - make_interval(secs => p_window_seconds)
            then v_now
            else public.api_rate_limits.window_started_at
        end,
        request_count = case
            when public.api_rate_limits.window_started_at
                 <= v_now - make_interval(secs => p_window_seconds)
            then 1
            else public.api_rate_limits.request_count + 1
        end,
        updated_at = v_now
    returning window_started_at, request_count
    into v_started, v_count;

    if v_count > p_limit then
        v_retry := greatest(
            1,
            ceil(extract(epoch from (
                v_started
                + make_interval(secs => p_window_seconds)
                - v_now
            )))::integer
        );

        return jsonb_build_object(
            'allowed', false,
            'retry_after', v_retry,
            'count', v_count
        );
    end if;

    delete from public.api_rate_limits
    where updated_at < v_now - interval '24 hours';

    return jsonb_build_object(
        'allowed', true,
        'retry_after', 0,
        'count', v_count
    );
end;
$$;

revoke all on function public.consume_api_rate_limit(text,integer,integer) from public;
revoke all on function public.consume_api_rate_limit(text,integer,integer) from anon;
revoke all on function public.consume_api_rate_limit(text,integer,integer) from authenticated;
grant execute on function public.consume_api_rate_limit(text,integer,integer) to service_role;


-- 2) Confirmación de pago reforzada.
-- Evita que un webhook tardío vuelva a descontar stock después de
-- un reembolso/contracargo o vuelva a procesar un pedido ya resuelto.
create or replace function public.confirmar_pago_pedido(
    p_pedido_id uuid,
    p_payment_id text
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
    v_estado text;
    v_payment_id text;
    v_falta_stock boolean;
begin
    select estado, mp_payment_id
    into v_estado, v_payment_id
    from public.pedidos
    where id = p_pedido_id
    for update;

    if not found then
        return jsonb_build_object('ok', false, 'reason', 'pedido_no_encontrado');
    end if;

    if v_estado = 'pagado' then
        return jsonb_build_object(
            'ok', true,
            'already_paid', true,
            'payment_id', v_payment_id
        );
    end if;

    if v_estado = 'pagado_revisar_stock' then
        return jsonb_build_object(
            'ok', false,
            'already_processed', true,
            'reason', 'stock_en_revision'
        );
    end if;

    if v_estado in ('reembolsado', 'contracargo') then
        return jsonb_build_object(
            'ok', false,
            'blocked', true,
            'reason', 'estado_terminal'
        );
    end if;

    select exists(
        select 1
        from public.pedido_items i
        left join public.productos p on p.id = i.producto_id
        where i.pedido_id = p_pedido_id
          and (p.id is null or p.stock < i.cantidad)
    )
    into v_falta_stock;

    if v_falta_stock then
        update public.pedidos
        set estado = 'pagado_revisar_stock',
            mp_payment_id = p_payment_id
        where id = p_pedido_id;

        return jsonb_build_object(
            'ok', false,
            'reason', 'stock_insuficiente'
        );
    end if;

    update public.productos p
    set stock = p.stock - i.cantidad,
        updated_at = now()
    from public.pedido_items i
    where i.pedido_id = p_pedido_id
      and i.producto_id = p.id;

    update public.pedidos
    set estado = 'pagado',
        mp_payment_id = p_payment_id
    where id = p_pedido_id;

    return jsonb_build_object('ok', true, 'paid', true);
end;
$$;

revoke all on function public.confirmar_pago_pedido(uuid,text) from public;
revoke all on function public.confirmar_pago_pedido(uuid,text) from anon;
revoke all on function public.confirmar_pago_pedido(uuid,text) from authenticated;
grant execute on function public.confirmar_pago_pedido(uuid,text) to service_role;


-- 3) Transiciones seguras para estados no aprobados.
-- Un evento pendiente/rechazado/cancelado nunca puede degradar un pedido
-- que ya fue pagado o revertido.
create or replace function public.registrar_estado_pago(
    p_pedido_id uuid,
    p_payment_id text,
    p_estado text
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
    v_estado text;
    v_payment_id text;
    v_estado_nuevo text := lower(coalesce(p_estado, ''));
begin
    if v_estado_nuevo not in (
        'pago_pendiente',
        'pago_rechazado',
        'pago_cancelado',
        'pago_revisar_monto',
        'reembolsado',
        'contracargo'
    ) then
        return jsonb_build_object('ok', false, 'reason', 'estado_no_permitido');
    end if;

    select estado, mp_payment_id
    into v_estado, v_payment_id
    from public.pedidos
    where id = p_pedido_id
    for update;

    if not found then
        return jsonb_build_object('ok', false, 'reason', 'pedido_no_encontrado');
    end if;

    if v_estado in ('reembolsado', 'contracargo') then
        return jsonb_build_object(
            'ok', true,
            'ignored', true,
            'reason', 'estado_terminal'
        );
    end if;

    if v_estado_nuevo in ('reembolsado', 'contracargo') then
        if v_estado not in ('pagado', 'pagado_revisar_stock', 'pago_revisar_monto') then
            return jsonb_build_object(
                'ok', true,
                'ignored', true,
                'reason', 'pedido_no_pagado'
            );
        end if;

        if nullif(v_payment_id, '') is not null
           and nullif(p_payment_id, '') is not null
           and v_payment_id <> p_payment_id
        then
            return jsonb_build_object(
                'ok', true,
                'ignored', true,
                'reason', 'payment_id_no_coincide'
            );
        end if;

        update public.pedidos
        set estado = v_estado_nuevo,
            mp_payment_id = coalesce(nullif(v_payment_id, ''), p_payment_id)
        where id = p_pedido_id;

        return jsonb_build_object('ok', true, 'updated', true);
    end if;

    if v_estado in ('pagado', 'pagado_revisar_stock', 'pago_revisar_monto') then
        return jsonb_build_object(
            'ok', true,
            'ignored', true,
            'reason', 'no_degradar_estado_pagado'
        );
    end if;

    update public.pedidos
    set estado = v_estado_nuevo,
        mp_payment_id = coalesce(nullif(p_payment_id, ''), mp_payment_id)
    where id = p_pedido_id;

    return jsonb_build_object('ok', true, 'updated', true);
end;
$$;

revoke all on function public.registrar_estado_pago(uuid,text,text) from public;
revoke all on function public.registrar_estado_pago(uuid,text,text) from anon;
revoke all on function public.registrar_estado_pago(uuid,text,text) from authenticated;
grant execute on function public.registrar_estado_pago(uuid,text,text) to service_role;


-- ===== dorado-final-hardening.sql =====
-- ============================================================
-- DORADO ARTÍCULOS DE PESCA — PARCHE FINAL PARA BASE NUEVA
-- Ejecutar DESPUÉS de supabase-setup.sql, upgrade-final.sql,
-- product-gallery.sql y security-hardening.sql.
-- ============================================================

-- Estado del email de confirmación. Permite reintentos sin duplicar envíos.
alter table public.pedidos
    add column if not exists email_confirmacion_estado text not null default 'pendiente',
    add column if not exists email_confirmacion_intentos integer not null default 0,
    add column if not exists email_confirmacion_actualizado timestamptz;

create or replace function public.claim_email_confirmacion(p_pedido_id uuid)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
    v_estado text;
    v_actualizado timestamptz;
begin
    select email_confirmacion_estado, email_confirmacion_actualizado
    into v_estado, v_actualizado
    from public.pedidos
    where id = p_pedido_id
    for update;

    if not found then
        return jsonb_build_object('claimed', false, 'reason', 'pedido_no_encontrado');
    end if;

    if v_estado = 'enviado' then
        return jsonb_build_object('claimed', false, 'reason', 'ya_enviado');
    end if;

    if v_estado = 'enviando'
       and v_actualizado is not null
       and v_actualizado > now() - interval '5 minutes'
    then
        return jsonb_build_object('claimed', false, 'reason', 'en_proceso');
    end if;

    update public.pedidos
    set email_confirmacion_estado = 'enviando',
        email_confirmacion_intentos = email_confirmacion_intentos + 1,
        email_confirmacion_actualizado = now()
    where id = p_pedido_id;

    return jsonb_build_object('claimed', true);
end;
$$;

revoke all on function public.claim_email_confirmacion(uuid) from public;
revoke all on function public.claim_email_confirmacion(uuid) from anon;
revoke all on function public.claim_email_confirmacion(uuid) from authenticated;
grant execute on function public.claim_email_confirmacion(uuid) to service_role;

create or replace function public.finalizar_email_confirmacion(
    p_pedido_id uuid,
    p_enviado boolean
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
begin
    update public.pedidos
    set email_confirmacion_estado = case when p_enviado then 'enviado' else 'pendiente' end,
        email_confirmacion_actualizado = now()
    where id = p_pedido_id;

    if not found then
        return jsonb_build_object('ok', false, 'reason', 'pedido_no_encontrado');
    end if;

    return jsonb_build_object('ok', true, 'sent', p_enviado);
end;
$$;

revoke all on function public.finalizar_email_confirmacion(uuid,boolean) from public;
revoke all on function public.finalizar_email_confirmacion(uuid,boolean) from anon;
revoke all on function public.finalizar_email_confirmacion(uuid,boolean) from authenticated;
grant execute on function public.finalizar_email_confirmacion(uuid,boolean) to service_role;

-- Confirmación de pago con bloqueo de productos en orden determinista.
-- Evita que dos pagos simultáneos descuenten la misma última unidad.
create or replace function public.confirmar_pago_pedido(
    p_pedido_id uuid,
    p_payment_id text
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
    v_estado text;
    v_payment_id text;
    v_falta_stock boolean;
begin
    select estado, mp_payment_id
    into v_estado, v_payment_id
    from public.pedidos
    where id = p_pedido_id
    for update;

    if not found then
        return jsonb_build_object('ok', false, 'reason', 'pedido_no_encontrado');
    end if;

    if v_estado = 'pagado' then
        return jsonb_build_object('ok', true, 'already_paid', true, 'payment_id', v_payment_id);
    end if;

    if v_estado = 'pagado_revisar_stock' then
        return jsonb_build_object('ok', false, 'already_processed', true, 'reason', 'stock_en_revision');
    end if;

    if v_estado in ('reembolsado', 'contracargo') then
        return jsonb_build_object('ok', false, 'blocked', true, 'reason', 'estado_terminal');
    end if;

    -- Bloquea todos los productos involucrados antes de verificar stock.
    perform p.id
    from public.productos p
    join (
        select producto_id, sum(cantidad)::integer as cantidad
        from public.pedido_items
        where pedido_id = p_pedido_id
        group by producto_id
    ) i on i.producto_id = p.id
    order by p.id
    for update;

    select exists(
        select 1
        from (
            select producto_id, sum(cantidad)::integer as cantidad
            from public.pedido_items
            where pedido_id = p_pedido_id
            group by producto_id
        ) i
        left join public.productos p on p.id = i.producto_id
        where p.id is null or p.stock < i.cantidad
    ) into v_falta_stock;

    if v_falta_stock then
        update public.pedidos
        set estado = 'pagado_revisar_stock',
            mp_payment_id = p_payment_id
        where id = p_pedido_id;
        return jsonb_build_object('ok', false, 'reason', 'stock_insuficiente');
    end if;

    update public.productos p
    set stock = p.stock - i.cantidad,
        updated_at = now()
    from (
        select producto_id, sum(cantidad)::integer as cantidad
        from public.pedido_items
        where pedido_id = p_pedido_id
        group by producto_id
    ) i
    where i.producto_id = p.id;

    update public.pedidos
    set estado = 'pagado',
        mp_payment_id = p_payment_id
    where id = p_pedido_id;

    return jsonb_build_object('ok', true, 'paid', true);
end;
$$;

revoke all on function public.confirmar_pago_pedido(uuid,text) from public;
revoke all on function public.confirmar_pago_pedido(uuid,text) from anon;
revoke all on function public.confirmar_pago_pedido(uuid,text) from authenticated;
grant execute on function public.confirmar_pago_pedido(uuid,text) to service_role;

-- El Admin puede leer pedidos pero desde el navegador solo modificar
-- el estado de preparación, nunca el estado de pago ni sus importes.
revoke update on table public.pedidos from authenticated;
grant select on table public.pedidos to authenticated;
grant update (preparacion_estado) on table public.pedidos to authenticated;
grant select on table public.pedido_items to authenticated;


-- ===== commerce-features.sql =====
-- ============================================================
-- DORADO ARTÍCULOS DE PESCA
-- Descuentos de productos + cupones + emails de estado de pago
-- Ejecutar UNA VEZ en Supabase SQL Editor sobre la base actual.
-- Es idempotente: puede volver a ejecutarse si una ejecución se corta.
-- ============================================================

-- 1) Descuentos por producto -------------------------------------------------
alter table public.productos
    add column if not exists descuento_porcentaje numeric(5,2) not null default 0;

update public.productos
set descuento_porcentaje = 0
where descuento_porcentaje is null;

do $$
begin
    if not exists (
        select 1 from pg_constraint where conname = 'productos_descuento_porcentaje_check'
    ) then
        alter table public.productos
            add constraint productos_descuento_porcentaje_check
            check (descuento_porcentaje >= 0 and descuento_porcentaje <= 90);
    end if;
end $$;

-- 2) Cupones ----------------------------------------------------------------
create table if not exists public.cupones (
    id uuid primary key default gen_random_uuid(),
    codigo text not null,
    tipo text not null default 'porcentaje',
    valor numeric(12,2) not null,
    minimo_compra numeric(12,2) not null default 0,
    activo boolean not null default true,
    vigente_desde timestamptz,
    vigente_hasta timestamptz,
    limite_usos integer,
    usos integer not null default 0,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint cupones_codigo_formato_check check (codigo = upper(codigo) and codigo ~ '^[A-Z0-9_-]{1,40}$'),
    constraint cupones_tipo_check check (tipo in ('porcentaje','fijo')),
    constraint cupones_valor_check check (valor > 0),
    constraint cupones_minimo_check check (minimo_compra >= 0),
    constraint cupones_limite_check check (limite_usos is null or limite_usos > 0),
    constraint cupones_usos_check check (usos >= 0),
    constraint cupones_fechas_check check (vigente_hasta is null or vigente_desde is null or vigente_hasta > vigente_desde),
    constraint cupones_porcentaje_check check (tipo <> 'porcentaje' or valor <= 100)
);

create unique index if not exists cupones_codigo_uidx on public.cupones (upper(codigo));
create index if not exists cupones_activo_idx on public.cupones (activo);

alter table public.cupones enable row level security;

drop policy if exists "Admins can view coupons" on public.cupones;
create policy "Admins can view coupons"
on public.cupones for select
to authenticated
using (public.is_admin());

drop policy if exists "Admins can insert coupons" on public.cupones;
create policy "Admins can insert coupons"
on public.cupones for insert
to authenticated
with check (public.is_admin());

drop policy if exists "Admins can update coupons" on public.cupones;
create policy "Admins can update coupons"
on public.cupones for update
to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "Admins can delete coupons" on public.cupones;
create policy "Admins can delete coupons"
on public.cupones for delete
to authenticated
using (public.is_admin());

revoke all on table public.cupones from anon;
grant select, insert, update, delete on table public.cupones to authenticated;
grant select, insert, update, delete on table public.cupones to service_role;

-- 3) Datos económicos y reintento de pago en pedidos -------------------------
alter table public.pedidos
    add column if not exists subtotal numeric(12,2) not null default 0,
    add column if not exists descuento_total numeric(12,2) not null default 0,
    add column if not exists cupon_id uuid,
    add column if not exists cupon_codigo text,
    add column if not exists mp_init_point text,
    add column if not exists pago_expira_at timestamptz;

update public.pedidos
set subtotal = total
where subtotal = 0 and coalesce(total,0) > 0;

do $$
begin
    if not exists (
        select 1 from pg_constraint where conname = 'pedidos_descuento_total_check'
    ) then
        alter table public.pedidos
            add constraint pedidos_descuento_total_check check (descuento_total >= 0);
    end if;

    if not exists (
        select 1 from pg_constraint where conname = 'pedidos_subtotal_check'
    ) then
        alter table public.pedidos
            add constraint pedidos_subtotal_check check (subtotal >= 0);
    end if;

    if not exists (
        select 1 from pg_constraint where conname = 'pedidos_cupon_id_fkey'
    ) then
        alter table public.pedidos
            add constraint pedidos_cupon_id_fkey
            foreign key (cupon_id) references public.cupones(id) on delete set null;
    end if;
end $$;

create index if not exists pedidos_cupon_id_idx on public.pedidos(cupon_id);
create index if not exists pedidos_pago_expira_at_idx on public.pedidos(pago_expira_at);

-- El backend server-side necesita estas columnas para checkout/webhooks.
grant select, insert, update on table public.pedidos to service_role;
grant select, insert on table public.pedido_items to service_role;
grant select, update on table public.productos to service_role;

-- 4) Control de emails por evento (evita duplicados de webhooks) -------------
create table if not exists public.pedido_email_eventos (
    pedido_id uuid not null references public.pedidos(id) on delete cascade,
    tipo text not null,
    estado text not null default 'pendiente',
    intentos integer not null default 0,
    actualizado_at timestamptz not null default now(),
    primary key (pedido_id, tipo),
    constraint pedido_email_tipo_check check (tipo in ('pending','confirmed','cancelled','refunded')),
    constraint pedido_email_estado_check check (estado in ('pendiente','enviando','enviado')),
    constraint pedido_email_intentos_check check (intentos >= 0)
);

alter table public.pedido_email_eventos enable row level security;
revoke all on table public.pedido_email_eventos from anon, authenticated;
grant select, insert, update on table public.pedido_email_eventos to service_role;

create or replace function public.claim_order_email(
    p_pedido_id uuid,
    p_tipo text
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
    v_estado text;
    v_actualizado timestamptz;
begin
    if p_tipo not in ('pending','confirmed','cancelled','refunded') then
        return jsonb_build_object('claimed', false, 'reason', 'tipo_invalido');
    end if;

    insert into public.pedido_email_eventos (pedido_id, tipo)
    values (p_pedido_id, p_tipo)
    on conflict (pedido_id, tipo) do nothing;

    select estado, actualizado_at
      into v_estado, v_actualizado
      from public.pedido_email_eventos
     where pedido_id = p_pedido_id and tipo = p_tipo
     for update;

    if not found then
        return jsonb_build_object('claimed', false, 'reason', 'pedido_no_encontrado');
    end if;

    if v_estado = 'enviado' then
        return jsonb_build_object('claimed', false, 'reason', 'ya_enviado');
    end if;

    if v_estado = 'enviando'
       and v_actualizado > now() - interval '5 minutes'
    then
        return jsonb_build_object('claimed', false, 'reason', 'en_proceso');
    end if;

    update public.pedido_email_eventos
       set estado = 'enviando',
           intentos = intentos + 1,
           actualizado_at = now()
     where pedido_id = p_pedido_id and tipo = p_tipo;

    return jsonb_build_object('claimed', true);
end;
$$;

revoke all on function public.claim_order_email(uuid,text) from public, anon, authenticated;
grant execute on function public.claim_order_email(uuid,text) to service_role;

create or replace function public.finalize_order_email(
    p_pedido_id uuid,
    p_tipo text,
    p_enviado boolean
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
begin
    update public.pedido_email_eventos
       set estado = case when p_enviado then 'enviado' else 'pendiente' end,
           actualizado_at = now()
     where pedido_id = p_pedido_id and tipo = p_tipo;

    if not found then
        return jsonb_build_object('ok', false, 'reason', 'evento_no_encontrado');
    end if;

    return jsonb_build_object('ok', true, 'sent', p_enviado);
end;
$$;

revoke all on function public.finalize_order_email(uuid,text,boolean) from public, anon, authenticated;
grant execute on function public.finalize_order_email(uuid,text,boolean) to service_role;

-- 5) Confirmación de pago: mantiene el control de stock actual y registra
--    un uso de cupón una sola vez cuando el pedido pasa a PAGADO. ------------
create or replace function public.confirmar_pago_pedido(
    p_pedido_id uuid,
    p_payment_id text
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
    v_estado text;
    v_payment_id text;
    v_falta_stock boolean;
    v_cupon_id uuid;
begin
    select estado, mp_payment_id, cupon_id
      into v_estado, v_payment_id, v_cupon_id
      from public.pedidos
     where id = p_pedido_id
     for update;

    if not found then
        return jsonb_build_object('ok', false, 'reason', 'pedido_no_encontrado');
    end if;

    if v_estado = 'pagado' then
        return jsonb_build_object('ok', true, 'already_paid', true, 'payment_id', v_payment_id);
    end if;

    if v_estado = 'pagado_revisar_stock' then
        return jsonb_build_object('ok', false, 'already_processed', true, 'reason', 'stock_en_revision');
    end if;

    if v_estado in ('reembolsado', 'contracargo') then
        return jsonb_build_object('ok', false, 'blocked', true, 'reason', 'estado_terminal');
    end if;

    perform p.id
      from public.productos p
      join (
          select producto_id, sum(cantidad)::integer as cantidad
            from public.pedido_items
           where pedido_id = p_pedido_id
           group by producto_id
      ) i on i.producto_id = p.id
     order by p.id
     for update;

    select exists(
        select 1
          from (
              select producto_id, sum(cantidad)::integer as cantidad
                from public.pedido_items
               where pedido_id = p_pedido_id
               group by producto_id
          ) i
          left join public.productos p on p.id = i.producto_id
         where p.id is null or p.stock < i.cantidad
    ) into v_falta_stock;

    if v_falta_stock then
        update public.pedidos
           set estado = 'pagado_revisar_stock',
               mp_payment_id = p_payment_id
         where id = p_pedido_id;
        return jsonb_build_object('ok', false, 'reason', 'stock_insuficiente');
    end if;

    update public.productos p
       set stock = p.stock - i.cantidad,
           updated_at = now()
      from (
          select producto_id, sum(cantidad)::integer as cantidad
            from public.pedido_items
           where pedido_id = p_pedido_id
           group by producto_id
      ) i
     where i.producto_id = p.id;

    if v_cupon_id is not null then
        update public.cupones
           set usos = usos + 1,
               updated_at = now()
         where id = v_cupon_id;
    end if;

    update public.pedidos
       set estado = 'pagado',
           mp_payment_id = p_payment_id
     where id = p_pedido_id;

    return jsonb_build_object('ok', true, 'paid', true);
end;
$$;

revoke all on function public.confirmar_pago_pedido(uuid,text) from public, anon, authenticated;
grant execute on function public.confirmar_pago_pedido(uuid,text) to service_role;

-- 6) Refrescar permisos del panel para descuento de productos ----------------
grant select, insert, update, delete on table public.productos to authenticated;

-- Fin.

-- =========================================================
-- HARDENING FINAL 2026-09-26
-- =========================================================
create or replace function public.is_admin()
returns boolean
language sql
stable
security invoker
set search_path = public
as $$
    select exists(
        select 1
        from public.admin_users
        where user_id = (select auth.uid())
    );
$$;

revoke all on function public.is_admin() from public, anon;
grant execute on function public.is_admin() to authenticated;

drop policy if exists "Admin can read own admin row" on public.admin_users;
create policy "Admin can read own admin row"
on public.admin_users
for select
to authenticated
using (user_id = (select auth.uid()));

drop policy if exists "Admins can delete orders" on public.pedidos;
create policy "Admins can delete orders"
on public.pedidos
for delete
to authenticated
using (public.is_admin());

grant delete on table public.pedidos to authenticated;

create or replace function public.admin_delete_orders(p_ids uuid[])
returns integer
language plpgsql
security invoker
set search_path = public
as $$
declare
    v_deleted integer := 0;
begin
    if (select auth.uid()) is null or not public.is_admin() then
        raise exception 'not_authorized' using errcode = '42501';
    end if;
    if p_ids is null or coalesce(array_length(p_ids,1),0)=0 or coalesce(array_length(p_ids,1),0)>200 then
        raise exception 'invalid_order_ids' using errcode = '22023';
    end if;
    delete from public.pedidos where id = any(p_ids);
    get diagnostics v_deleted = row_count;
    return v_deleted;
end;
$$;

revoke all on function public.admin_delete_orders(uuid[]) from public, anon;
grant execute on function public.admin_delete_orders(uuid[]) to authenticated;

create index if not exists pedido_items_producto_id_idx on public.pedido_items(producto_id);

