-- DORADO ARTÍCULOS DE PESCA
-- Fuente local segura para reseñas reales sincronizadas desde Google Business Profile.

create table if not exists public.resenas_google (
  id bigint generated by default as identity primary key,
  external_id text unique,
  autor text not null,
  avatar_url text,
  calificacion smallint not null check (calificacion between 1 and 5),
  comentario text,
  fecha_resena timestamptz,
  fuente_url text,
  activa boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.resenas_google enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname='public' and tablename='resenas_google' and policyname='Public can view active Google reviews'
  ) then
    create policy "Public can view active Google reviews"
    on public.resenas_google for select to anon, authenticated
    using (activa = true);
  end if;
end
$$;

grant select on table public.resenas_google to anon, authenticated;
grant all on table public.resenas_google to service_role;

create index if not exists resenas_google_activa_calificacion_idx
  on public.resenas_google (activa, calificacion desc, fecha_resena desc);
