-- ============================================================
-- DORADO ARTÍCULOS DE PESCA — PROMOCIONES + EMAILS DE ESTADO
-- Descuentos por producto, cupones, reintento de pago por 24 h
-- y deduplicación de emails por evento.
-- ============================================================

alter table public.productos
    add column if not exists descuento_porcentaje numeric(5,2) not null default 0;

do $$
begin
    if not exists (
        select 1 from pg_constraint
        where conname = 'productos_descuento_porcentaje_rango'
          and conrelid = 'public.productos'::regclass
    ) then
        alter table public.productos
            add constraint productos_descuento_porcentaje_rango
            check (descuento_porcentaje >= 0 and descuento_porcentaje <= 95);
    end if;
end $$;

alter table public.pedidos
    add column if not exists subtotal numeric(12,2),
    add column if not exists descuento_productos numeric(12,2) not null default 0,
    add column if not exists descuento_cupon numeric(12,2) not null default 0,
    add column if not exists cupon_codigo text,
    add column if not exists expira_pago_at timestamptz;

update public.pedidos
set subtotal = coalesce(subtotal, total),
    expira_pago_at = coalesce(expira_pago_at, created_at + interval '24 hours')
where subtotal is null or expira_pago_at is null;

alter table public.pedidos
    alter column subtotal set default 0,
    alter column subtotal set not null,
    alter column expira_pago_at set default (now() + interval '24 hours'),
    alter column expira_pago_at set not null;

do $$
begin
    if not exists (
        select 1 from pg_constraint
        where conname = 'pedidos_descuentos_no_negativos'
          and conrelid = 'public.pedidos'::regclass
    ) then
        alter table public.pedidos
            add constraint pedidos_descuentos_no_negativos
            check (
                subtotal >= 0
                and descuento_productos >= 0
                and descuento_cupon >= 0
            );
    end if;
end $$;

alter table public.pedido_items
    add column if not exists precio_lista numeric(12,2);

update public.pedido_items
set precio_lista = precio_unitario
where precio_lista is null;

alter table public.pedido_items
    alter column precio_lista set default 0,
    alter column precio_lista set not null;

do $$
begin
    if not exists (
        select 1 from pg_constraint
        where conname = 'pedido_items_precio_lista_no_negativo'
          and conrelid = 'public.pedido_items'::regclass
    ) then
        alter table public.pedido_items
            add constraint pedido_items_precio_lista_no_negativo
            check (precio_lista >= 0);
    end if;
end $$;

create table if not exists public.cupones (
    id bigint generated by default as identity primary key,
    codigo text not null,
    tipo text not null default 'porcentaje',
    valor numeric(12,2) not null,
    minimo_compra numeric(12,2) not null default 0,
    activo boolean not null default true,
    valido_desde timestamptz,
    valido_hasta timestamptz,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint cupones_tipo_valido check (tipo in ('porcentaje','fijo')),
    constraint cupones_valor_positivo check (valor > 0),
    constraint cupones_minimo_no_negativo check (minimo_compra >= 0),
    constraint cupones_porcentaje_rango check (tipo <> 'porcentaje' or valor <= 100)
);

create unique index if not exists cupones_codigo_upper_uidx
on public.cupones ((upper(trim(codigo))));

alter table public.cupones enable row level security;

drop policy if exists "Admins manage coupons" on public.cupones;
create policy "Admins manage coupons"
on public.cupones
for all
to authenticated
using ((select public.is_admin()))
with check ((select public.is_admin()));

revoke all on table public.cupones from anon;
grant select, insert, update, delete on table public.cupones to authenticated;
grant usage, select on sequence public.cupones_id_seq to authenticated;

create table if not exists public.pedido_email_eventos (
    pedido_id uuid not null references public.pedidos(id) on delete cascade,
    evento text not null,
    estado text not null default 'pendiente',
    intentos integer not null default 0,
    actualizado_at timestamptz,
    enviado_at timestamptz,
    primary key (pedido_id, evento),
    constraint pedido_email_eventos_evento_valido
        check (evento in ('pagado','pendiente','cancelado')),
    constraint pedido_email_eventos_estado_valido
        check (estado in ('pendiente','enviando','enviado')),
    constraint pedido_email_eventos_intentos_no_negativos
        check (intentos >= 0)
);

alter table public.pedido_email_eventos enable row level security;
revoke all on table public.pedido_email_eventos from public;
revoke all on table public.pedido_email_eventos from anon;
revoke all on table public.pedido_email_eventos from authenticated;
grant select, insert, update, delete on table public.pedido_email_eventos to service_role;

create or replace function public.claim_pedido_email_evento(
    p_pedido_id uuid,
    p_evento text
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
    v_evento text := lower(trim(coalesce(p_evento, '')));
    v_estado text;
    v_actualizado timestamptz;
begin
    if v_evento not in ('pagado','pendiente','cancelado') then
        return jsonb_build_object('claimed', false, 'reason', 'evento_no_permitido');
    end if;

    if not exists (select 1 from public.pedidos where id = p_pedido_id) then
        return jsonb_build_object('claimed', false, 'reason', 'pedido_no_encontrado');
    end if;

    insert into public.pedido_email_eventos (pedido_id, evento)
    values (p_pedido_id, v_evento)
    on conflict (pedido_id, evento) do nothing;

    select estado, actualizado_at
    into v_estado, v_actualizado
    from public.pedido_email_eventos
    where pedido_id = p_pedido_id
      and evento = v_evento
    for update;

    if v_estado = 'enviado' then
        return jsonb_build_object('claimed', false, 'reason', 'ya_enviado');
    end if;

    if v_estado = 'enviando'
       and v_actualizado is not null
       and v_actualizado > now() - interval '5 minutes'
    then
        return jsonb_build_object('claimed', false, 'reason', 'en_proceso');
    end if;

    update public.pedido_email_eventos
    set estado = 'enviando',
        intentos = intentos + 1,
        actualizado_at = now()
    where pedido_id = p_pedido_id
      and evento = v_evento;

    return jsonb_build_object('claimed', true);
end;
$$;

revoke all on function public.claim_pedido_email_evento(uuid,text) from public;
revoke all on function public.claim_pedido_email_evento(uuid,text) from anon;
revoke all on function public.claim_pedido_email_evento(uuid,text) from authenticated;
grant execute on function public.claim_pedido_email_evento(uuid,text) to service_role;

create or replace function public.finalizar_pedido_email_evento(
    p_pedido_id uuid,
    p_evento text,
    p_enviado boolean
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
    v_evento text := lower(trim(coalesce(p_evento, '')));
begin
    update public.pedido_email_eventos
    set estado = case when p_enviado then 'enviado' else 'pendiente' end,
        actualizado_at = now(),
        enviado_at = case when p_enviado then now() else enviado_at end
    where pedido_id = p_pedido_id
      and evento = v_evento;

    if not found then
        return jsonb_build_object('ok', false, 'reason', 'evento_no_encontrado');
    end if;

    return jsonb_build_object('ok', true, 'sent', p_enviado);
end;
$$;

revoke all on function public.finalizar_pedido_email_evento(uuid,text,boolean) from public;
revoke all on function public.finalizar_pedido_email_evento(uuid,text,boolean) from anon;
revoke all on function public.finalizar_pedido_email_evento(uuid,text,boolean) from authenticated;
grant execute on function public.finalizar_pedido_email_evento(uuid,text,boolean) to service_role;
